### ISSUE TITLE
İos publish

### ISSUE THREAD

**Issue by abdurrahmanekr** [serhatboyraz/bibilgimobile#5]
Merhaba @serhatboyraz dün bana bir [soru](http://www.avarekodcu.com/konu/25/react-native-ile-ilginc-bilgiler-uygulamasi-bibilgi-acik-kaynak-projesi) geldi:
![ekran goruntusu 2017-07-22 08 41 11](https://user-images.githubusercontent.com/15075759/28488751-8a0e6546-6eb9-11e7-8786-7ba2ea44ab01.png)
Bu konu hakkında düşüncelerin nedir?

**Comment by ahmetozalp** [comment]
Teşşekurler yönlendirmen için.

**Comment by serhatboyraz** [comment]
İlgili lisans kaynak belirterek bunu yapabileceğini söylüyor. Ancak servis tarafında değişiklik yapılması gerekecektir. Ek olarak sertifikalar oluşturulmalı ve serviste kullanılmalı. İlgili değişiklik için detaylı konuşabiliriz.

**Comment by ahmetozalp** [comment]
neyse bunlarla uraşıcak okadar çok zamanım yok :) Teşşekıurler genede en azından sizi tanımış oldum

**Comment by roalibiten** [comment]
React-Native ile IOS ve Android'e kolayca uygulama çıkartabilmemiz gerekmiyor mu? Yoksa bu işlem zor bir işlem mi? Yani ben bir uyguluma geliştirdiğimde bunu hem Android hem IOS 'ta çalışır hale getirmem çok mu zaman alır?
